### ISSUE TITLE
Add DaCy

### ISSUE THREAD

**Issue by KennethEnevoldsen** [fnielsen/awesome-danish#11]
Hej Finn,

Just wanted to let you know that you might want to add the danish implementation of DaCy to this very comprehensive list.

https://github.com/KennethEnevoldsen/DaCy

Thanks for your great work.
Kenneth

**Comment by fnielsen** [comment]
Thanks for the tip! I have added to in one paragraph. I should be adding it some other paragraphs too.

**Comment by fnielsen** [comment]
Listed under "Fundamental processing" now.
