### ISSUE TITLE
another danish sentiment analysis dataset

### ISSUE THREAD

**Issue by AlessandroGianfelici** [fnielsen/awesome-danish#14]
Dear all,

I am an NLP data scientist from Italy. As a part of a personal project, I am collecting customer reviews written in several languages from the web. I want to make those datasets available for everyone, so I was wandering if the danish dataset could be added to this very comprehensive list. 

https://github.com/AlessandroGianfelici/danish_reviews_dataset

Thank you for your awesome work!
Best,
Alessandro

**Comment by fnielsen** [comment]
Added https://github.com/fnielsen/awesome-danish/commit/774a7290de21107ea004d6a155a103254fbd5b96#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

Thanks for the resource!
