### ISSUE TITLE
Add to awesome-nlp?

### ISSUE THREAD

**Issue by NirantK** [fnielsen/awesome-danish#6]
Hey Nielsen, 

This is quite amazing. I'd love to have this repo more accessible and visible. Can you consider adding a PR to https://github.com/keon/awesome-nlp ? 

About: Awesome NLP is listed in the official Github ML Collection and recommended by Stanford courses for NLP Review. We already list a bunch of non-English resources. 

We can consider either linking to Awesome-Danish or absorbing Danish specific resources in a separate section. Whatever you prefer.

**Comment by fnielsen** [comment]
Thanks very much for making me aware of the awesome-nlp resource. I have made af PR with a link to awesome-danish for now.
